### ISSUE TITLE
Latency of TAGE-SC-L

### ISSUE THREAD

**Issue by Vtecbest** [siavashzk/BranchNet#4]
Hi, may I ask a simple question about your paper? In your paper you said TAGE-SC-L costs 4 cycles to predict, could you please explain why? I can just count 3, maybe I lost some precedures. Thanks!

**Comment by siavashzk** [comment]
I provided the answer to your question below, but can you tell me how you arrived at the number 3? What do you mean by counting "procedures"?

The latency is just an estimate using CACTI for large structure accesses and manually counting gate delays for logic structures.  Note that a more accurate estimate of latency needs implementing TAGE-SC-L in RTL and using modern synthesis and routing tools to measure the latency of a specific design.

Quoting the paper, this is what we assumed TAGE-SC-L's critical path to be: "The critical path of TAGE-SC-L: accessing banked TAGE tables, tag comparisons, TAGE mux tree (with a depth of log(n)), selection logic for alternative prediction and the loop predictor, accessing the statistical corrector GEHL tables, a 20-input 6-bit adder tree, and final selection logic."

In comparison, this is how BranchNet's latency is estimated. "The critical path of updating the convolutional histories consists of hashing the most recent branches, the convolution table look-up, an addition (7-bit running sum), quantization,
and insertion into a convolution history buffer. Using CACTI [39] for the table lookups and counting the gate delays of the
arithmetic operations, we computed the update latency to be roughly equal to the latency of a 64-bit Kogge-Stone adder (21
gate delays). Since 64-bit additions are single-cycle operations in modern processors [40], we estimate that Mini-BranchNet updates are also single-cycle operations. The critical path of the prediction pipeline for a 2KB Mini-BranchNet model includes the weight table look-up, the selection of the convolutional history, and a forward pass of the fully-connected layers (a 4-bit multiply, a 110-input 8-bit adder tree, a comparison, and accessing a 1024-entry table). The prediction latency is roughly 4 times the latency of a 64-bit Kogge-Stone adder. The latency of a 64KB TAGE-SC-L5
is 1.1 times the latency of the Mini-BranchNet inference engine. Thus, we conservatively estimate both Mini-BranchNet and 64KB TAGE-SC-L are 4-cycle predictors."

**Comment by Vtecbest** [comment]
I do consider it in RTL way. In your assumption, "The critical path of TAGE-SC-L: accessing banked TAGE tables, tag comparisons, TAGE mux tree (with a depth of log(n)), selection logic for alternative prediction and the loop predictor, accessing the statistical corrector GEHL tables, a 20-input 6-bit adder tree, and final selection logic." , does this mean:
stage1: access TAGE table, tag comparisons, TAGE mux tree, access loop predictor,
stage2:  access the statistical corrector GEHL tables,
stage3: a 20-input 6-bit adder tree,
stage4: final selection logic.
In my view, corrector GEHL tables accessing and TAGE table accessing can be done concurrently（access GEHL tables to get ctr of all confidence and then use a Mux to select ），that's how I get 3 cycles.
![image](https://user-images.githubusercontent.com/72300677/155129617-3b574de2-a3bb-42ca-80a1-56f7ddcf75e5.png)

**Comment by siavashzk** [comment]
I see. If you actually implement the predictor in RTL, and synthesized and routed using a specific technology, that is more accurate than counting gate delays. Technically, you still need the complete design of a core to know what the cycle time is. Basically, the more you simulate and design, the more accurate your estimation is. I'm not sure exactly how you're estimating your cycle time.

I did not actually design a 4-stage RTL design, so I do not know what the 4 stages look like. However, your proposed 4 stages do not seem balanced. The final selection logic is probably has a much shorter latency than the other stages. You want to divide the latency across all stages equally, and the stage boundaries do not have to be at the boundaries of the high-level components.

I suppose you could access TAGE and GEHL tables concurrently and then use a mux to select the correct GEHL entries based on TAGE's output. But note that one of the SC tables is indexed by 5 TAGE bits, meaning you need to access 32 entries, when only really needing 1 of them. You also need to include the 32-to-1 mux in the critical path. I do not know which way is faster.

**Comment by Vtecbest** [comment]
Ok,  thanks for your suggestion, I will consider it seriouly.

**Comment by siavashzk** [comment]
You're welcome!
